version: '2'

services:
    haproxy:
        build:
            context: ./haproxy
        links: 
            - node1:node1
            - node2:node2
        ports: 
            - "80:80"
    node1:
        image: jboss/wildfly
    node2:
        image: jboss/wildfly